apiVersion: apps/v1
kind: Deployment               
metadata:
  name: rge-http-server    
spec:
  replicas: 3               
  selector:
    matchLabels:
      app: rge-http-server       
  template:                      
    metadata:
      labels:                    
        app: rge-http-server
    spec:                        
      containers:
      - name: rge-grpc-server
        image: zeihanaulia/rge-grpc-server:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001 
        livenessProbe:           
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          
          httpGet:
            path: /readiness
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    