apiVersion: apps/v1
kind: Deployment               
metadata:
  name: rge-http-server    
spec:         
  selector:
    matchLabels:
      app: rge-http-server       
  template:                      
    metadata:
      labels:                    
        app: rge-http-server
    spec:                        
      containers:
      - name: rge-http-server
        image: zeihanaulia/rge-http-server:1.0.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2" 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001 
        livenessProbe:           
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          
          httpGet:
            path: /readiness
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    
      - name: rge-http-server-2
        image: zeihanaulia/rge-http-server-2:1.0.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2" 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3002
        livenessProbe:           
          httpGet:
            path: /health
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          
          httpGet:
            path: /readiness
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    
---
apiVersion: v1
kind: Service
metadata:
  name: rge-http-server-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  - name: http-2
    port: 3002
    targetPort: 3002
  selector:
    app: rge-http-server